<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#model-selection" data-toc-modified-id="model-selection-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>model selection</a></span><ul class="toc-item"><li><span><a href="#Finding-the-indices-for-KFold" data-toc-modified-id="Finding-the-indices-for-KFold-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Finding the indices for <code>KFold</code></a></span></li><li><span><a href="#LeaveOneGroupOut" data-toc-modified-id="LeaveOneGroupOut-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span><code>LeaveOneGroupOut</code></a></span></li></ul></li><li><span><a href="#Training-models-in-crosvalidation-using-GridsearchCV" data-toc-modified-id="Training-models-in-crosvalidation-using-GridsearchCV-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Training models in crosvalidation using GridsearchCV</a></span><ul class="toc-item"><li><span><a href="#Saved-metrics-in-a-GridSearchCV-object" data-toc-modified-id="Saved-metrics-in-a-GridSearchCV-object-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Saved metrics in a <code>GridSearchCV</code> object</a></span><ul class="toc-item"><li><span><a href="#Configurations-of--Hyperparameters-tested" data-toc-modified-id="Configurations-of--Hyperparameters-tested-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Configurations of  Hyperparameters tested</a></span></li></ul></li></ul></li><li><span><a href="#Generating-all-possible-combinations-of-hyperparameters" data-toc-modified-id="Generating-all-possible-combinations-of-hyperparameters-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Generating all possible combinations of hyperparameters</a></span><ul class="toc-item"><li><span><a href="#Ranking-results-of-the-crossvalidation-process" data-toc-modified-id="Ranking-results-of-the-crossvalidation-process-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Ranking results of the crossvalidation process</a></span></li><li><span><a href="#Creating-your-own-GridSearchCV" data-toc-modified-id="Creating-your-own-GridSearchCV-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Creating your own <code>GridSearchCV</code></a></span><ul class="toc-item"><li><span><a href="#Training-using-crosvalidation-a-given-model" data-toc-modified-id="Training-using-crosvalidation-a-given-model-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Training using crosvalidation a given model</a></span></li><li><span><a href="#TODO:-Make-a-function-that-given-cv_results_df-and-path_folder..." data-toc-modified-id="TODO:-Make-a-function-that-given-cv_results_df-and-path_folder...-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>TODO: Make a function that given cv_results_df and path_folder...</a></span></li></ul></li></ul></li><li><span><a href="#Finding-indices-with-GroupKFold" data-toc-modified-id="Finding-indices-with-GroupKFold-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Finding indices with <code>GroupKFold</code></a></span></li></ul></div>

# model selection


In [1]:
import sklearn
import numpy as np
import pandas as pd


## Finding the indices for `KFold`

The class `KFold` allows us to generate the train and validation indicies for performing training and validation indicies with different parts of our data.


In [2]:
from sklearn.model_selection import KFold
X = np.random.randn(100,4)
X.shape

(100, 4)

In [3]:
folds = KFold(10,shuffle=False)
splits = folds.split(X)
for fold, (tr_ind,va_ind) in enumerate(splits):
    print(fold, va_ind)

0 [0 1 2 3 4 5 6 7 8 9]
1 [10 11 12 13 14 15 16 17 18 19]
2 [20 21 22 23 24 25 26 27 28 29]
3 [30 31 32 33 34 35 36 37 38 39]
4 [40 41 42 43 44 45 46 47 48 49]
5 [50 51 52 53 54 55 56 57 58 59]
6 [60 61 62 63 64 65 66 67 68 69]
7 [70 71 72 73 74 75 76 77 78 79]
8 [80 81 82 83 84 85 86 87 88 89]
9 [90 91 92 93 94 95 96 97 98 99]


If shuffle is true then we sample all rows from our dataset randomly

In [4]:

folds = KFold(10,shuffle=True)
splits = folds.split(X)
for tr_ind,va_ind in splits:
    print(va_ind)

[ 9 19 29 46 68 84 85 86 89 98]
[ 6 15 35 38 53 60 77 92 93 94]
[21 23 28 49 58 62 72 76 88 96]
[ 3  4 13 34 43 52 54 57 80 81]
[ 0 10 24 27 32 42 47 73 97 99]
[17 22 25 30 40 75 79 82 90 95]
[12 18 33 37 50 64 65 78 83 91]
[11 16 20 36 41 44 51 55 66 71]
[ 1  5 26 39 48 59 61 70 74 87]
[ 2  7  8 14 31 45 56 63 67 69]


##  `LeaveOneGroupOut`

- Provides train/test indices to split data according to a third-party provided group. 

- This group information can be used to encode arbitrary domain specific stratifications of the samples as integers.


Now let us load the boston dataset and make a group that we will call `not_24`


In [282]:
from sklearn import datasets
dataset = sklearn.datasets.load_boston()

In [284]:
X = dataset.data
y = dataset.target
X_df = pd.DataFrame(X)

In [285]:
X_df.head()

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [286]:
X_df[8].unique()

array([ 1.,  2.,  3.,  5.,  4.,  8.,  6.,  7., 24.])

Let us consider a case where we might want the train splits to be divided in two groups A and B

- A: examples which at column 8 have values in `[1,  2,  3,  4,  5,  6,  7,  8]` 
- B: examples at which column 9 takes value  `24`.



In [321]:
value_24 = X_df[8] != 24
value_24 = np.array(value_24.values, dtype="int")

In [322]:
X.shape, not_24.shape

((506, 13), (506,))

In [329]:
from sklearn import linear_model
from sklearn import neural_network

cv   = sklearn.model_selection.LeaveOneGroupOut()
clf  = sklearn.linear_model.LinearRegression()
grid = sklearn.model_selection.GridSearchCV(clf, param_grid={}, cv=cv, 
                                            return_train_score=True, iid=True, n_jobs=-1)

grid.fit(X,y, groups=value_24)

GridSearchCV(cv=LeaveOneGroupOut(), error_score='raise-deprecating',
       estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False),
       fit_params=None, iid=True, n_jobs=-1, param_grid={},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [330]:
grid.cv_results_

{'mean_fit_time': array([0.00095105]),
 'std_fit_time': array([6.19888306e-05]),
 'mean_score_time': array([0.00039613]),
 'std_score_time': array([1.07288361e-06]),
 'params': [{}],
 'split0_test_score': array([-6.59688586]),
 'split1_test_score': array([-6.75857278e+19]),
 'mean_test_score': array([-4.99546684e+19]),
 'std_test_score': array([2.96774953e+19]),
 'rank_test_score': array([1], dtype=int32),
 'split0_train_score': array([0.86686183]),
 'split1_train_score': array([0.68323554]),
 'mean_train_score': array([0.77504868]),
 'std_train_score': array([0.09181314])}

In [331]:
grid.cv_results_['split0_train_score'], grid.cv_results_['split1_test_score'] 

(array([0.86686183]), array([-6.75857278e+19]))

Notice that one of the errors (the one in split1) is huge. 

This happens because one of the experiments in the GridSearchCV will consist on taking the examples  from B as training set (and it is very small) and then use the values in A as validation set (which is very big).

In [337]:
from sklearn import linear_model
from sklearn import neural_network

cv   = sklearn.model_selection.LeaveOneGroupOut()
clf  = sklearn.linear_model.LinearRegression()
grid = sklearn.model_selection.GridSearchCV(clf, param_grid={}, cv=cv, 
                                            return_train_score=True, iid=True, n_jobs=-1)

values_in_col8 = np.array(X_df[8].values, dtype="int")

grid.fit(X,y, groups=values_in_col8)

GridSearchCV(cv=LeaveOneGroupOut(), error_score='raise-deprecating',
       estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False),
       fit_params=None, iid=True, n_jobs=-1, param_grid={},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [339]:
grid.cv_results_

{'mean_fit_time': array([0.00112086]),
 'std_fit_time': array([0.000122]),
 'mean_score_time': array([0.00059387]),
 'std_score_time': array([3.01011142e-05]),
 'params': [{}],
 'split0_test_score': array([0.70028178]),
 'split1_test_score': array([0.77076574]),
 'split2_test_score': array([0.64766753]),
 'split3_test_score': array([0.70385404]),
 'split4_test_score': array([0.64780526]),
 'split5_test_score': array([-1.95031015]),
 'split6_test_score': array([0.3699049]),
 'split7_test_score': array([0.69561196]),
 'split8_test_score': array([-6.59688586]),
 'mean_test_score': array([-1.36260276]),
 'std_test_score': array([3.16246777]),
 'rank_test_score': array([1], dtype=int32),
 'split0_train_score': array([0.74100996]),
 'split1_train_score': array([0.73639286]),
 'split2_train_score': array([0.7369053]),
 'split3_train_score': array([0.73722303]),
 'split4_train_score': array([0.71793616]),
 'split5_train_score': array([0.74817225]),
 'split6_train_score': array([0.74326855]),
 

# Training models in crosvalidation using GridsearchCV

In [389]:
from sklearn.model_selection import GridSearchCV
from sklearn import datasets
from sklearn.datasets import *

In [390]:
dataset = sklearn.datasets.california_housing.fetch_california_housing()

In [391]:
X = dataset.data
y = dataset.target

X.shape, y.shape

((20640, 8), (20640,))

In [392]:
X_tr, X_te, y_tr, y_te = sklearn.model_selection.train_test_split(X,y, random_state=1234)

X_tr.shape, y_tr.shape, X_te.shape, y_te.shape

((15480, 8), (15480,), (5160, 8), (5160,))

In [393]:
from sklearn import ensemble
from sklearn.ensemble import *

rf = sklearn.ensemble.RandomForestRegressor()

param_grid = {"max_depth":[5,None,10], "max_features":["auto",0.5]}

In [394]:
rf_grid = sklearn.model_selection.GridSearchCV(rf, 
                                               param_grid=param_grid,
                                               cv=4,
                                               n_jobs=-1)

In [395]:
rf_grid.fit(X_tr, y_tr)

/Users/david/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


GridSearchCV(cv=4, error_score='raise-deprecating',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'max_depth': [5, None, 10], 'max_features': ['auto', 0.5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [396]:
rf_grid.best_estimator_

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=0.5, max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

## Saved metrics in a `GridSearchCV` object

After fitting a `GridsearchCV` object we can inspect the information saved during crossvalidation inside the field `.cv_results_`.

In [397]:
list(rf_grid.cv_results_.keys())

['mean_fit_time',
 'std_fit_time',
 'mean_score_time',
 'std_score_time',
 'param_max_depth',
 'param_max_features',
 'params',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'mean_test_score',
 'std_test_score',
 'rank_test_score',
 'split0_train_score',
 'split1_train_score',
 'split2_train_score',
 'split3_train_score',
 'mean_train_score',
 'std_train_score']

###  Configurations of  Hyperparameters tested

All the combinations of parameters tested are kept in `'params'`

In [ ]:
rf_grid.cv_results_["params"]

The different scores for each of the CV splits are found in `splitsK_test_score`.

In this case we have 4 arrays because we used `cv=4` when we instanciated `rf_grid`.

```
'split0_test_score'
'split1_test_score'
'split2_test_score'
'split3_test_score'
 ```
 
 Each array contains  possition `k` the test results of the k'th combination of hyperparameters.

In [ ]:
rf_grid.n_splits_

In [ ]:
all_scores = [rf_grid.cv_results_[f"split{i}_test_score" ] for i in range(4)]
all_scores

In [ ]:
rf_grid.best_score_

Notice that `rf_grid.best_score_` is different than `np.max(all_scores)`.

The best score is found using the mean value of the crossvalidation scores.

Therefore `rf_grid.best_score_= np.max(rf_grid.cv_results_["mean_test_score"])`

In [ ]:
np.max(rf_grid.cv_results_["mean_test_score"]), rf_grid.best_score_

In [ ]:
rf_grid.cv_results_["mean_test_score"]

Notice that we can compute `mean_test_score` simpy computing the mean
over the different results in the different splits of the crossvalidation process.

In [ ]:
np.array(all_scores).mean(axis=0)

# Generating all possible combinations of hyperparameters

In [ ]:
from itertools import product

In [ ]:
param_grid

The function product can take as input several iterators and it will generate
all the combinations of the values in the iterators

In [ ]:
[x for x in product(["a","b","c"],[1,2])]

We can use it to generate the combinations of different hyperparamaters

In [ ]:
[x for x in product(param_grid["max_depth"], param_grid["max_features"])]

the `*` notation allows us to generate a correctly formated input for `product`

In [ ]:
combination_params_values = [x for x in product(*param_grid.values())]
combination_params_values

Notice that we can then write the name of the param for each component

In [ ]:
params_keys = list(param_grid.keys())

for values in combination_params_values:
    print(dict(zip(param_grid.keys(),values)))

We can do all this in a single function that will generate the list with the combinations we want to explore given an space of hyperparameter values.

In [ ]:
def generate_params(param_grid):
    combination_params_values = [x for x in product(*param_grid.values())]
    params = []
    for values in combination_params_values:
        params.append(dict(zip(param_grid.keys(),values)))
    return params

In [ ]:
generate_params(param_grid)

Notice that this is the same as 

In [ ]:
rf_grid.cv_results_["params"]

## Ranking results of the crossvalidation process

All combinations of hyperparameters are stored in **`.cv_results_["params"]`**

We can visuallize in a single dataframe the differnet pa

In [ ]:
results = pd.DataFrame({"params": rf_grid.cv_results_["params"], 
                        "std_test_score": rf_grid.cv_results_["std_test_score"],
                        "mean_test_score": rf_grid.cv_results_["mean_test_score"],
                       })

In [ ]:
results = results.sort_values(by=["mean_test_score"], ascending=False)
results

We can also see the order (rank) of each parameter configuration in **`.cv_results_["rank_test_score"]`**.

In [ ]:
rank_test_score = rf_grid.cv_results_["rank_test_score"]
rank_test_score

Notice that **results of the grid search are sorted by `rf_grid.cv_results_["rank_test_score"]`.**

In [ ]:
[rf_grid.cv_results_["params"][k-1] for k in rank_test_score]

##### Ranking the results of crossvalidation: 1:best result, 2:second best result etc...

We can find in `rank_test_score` a ranking of the best (1) to the worst (6) results

In [ ]:
rf_grid.cv_results_["rank_test_score"]

We can generate this vector using `scipy.stats.rankdata` in order to rank the solutions according to `mean_test_score`

In [ ]:
import scipy
rank = scipy.stats.rankdata(-rf_grid.cv_results_["mean_test_score"],method='ordinal')
rank

## Creating your own `GridSearchCV` 

In [ ]:
param_grid = {"max_depth":[5,None,10], "max_features":["auto",0.5]}

In [ ]:
generate_params(param_grid)

In [ ]:
rf = sklearn.ensemble.RandomForestRegressor()

### Training using crosvalidation a given model

We want to have code that can train for each combination in `param_grid` we would like to train `cv` models and save the scores
of the different fitted models.

In [ ]:
param_grid

In [ ]:
rf

In [ ]:
def model_str(model, cv, params_combination):

    final_name = type(model).__name__ + "__fold{:02d}".format(cv)
    for item in params_combination.items():
        final_name += "__"
        final_name += item[0]+"=" +str(item[1])
        
    return final_name + ".joblib"


In [ ]:
params_combinations = generate_params(param_grid)
model_str(rf,2, params_combinations[0])

In [ ]:
import os
os.listdir("./")

In [ ]:
from copy import deepcopy
import joblib
from joblib import dump, load
from pathlib import Path
from sklearn.metrics import roc_auc_score
import datetime


def CVfit(X, y, model, cv, param_grid, scorer, path_folder="",
          save_models=False, save_summary=True, add_time=False, verbose=0):
    
    """
    
    Important notes:
    
    - By default this method uses the model.score function to score the test results.
    
    - If `scorer="roc_auc_score"` or `scorer=sklearn.metrics.roc_auc_score` then the method uses 
    `model.predict_proba` instead of `model.predict` when scoring the predictions.
    
    """
    
    cv_results_params = generate_params(param_grid)
    folds = KFold(cv,shuffle=False)
    cv_results_ = {}
    cv_results_["params"] = cv_results_params
    
    if add_time:
        now = datetime.datetime.now()
        time_id = f"__{now.hour}:{now.minute}:{now.second}__{now.day}-{now.month}-{now.year}"
        path_folder = path_folder +  time_id       
    
    for fold in range(cv):
        cv_results_[f"split{fold}_test_score"] = np.array([])
    
    # Create target Directory if don't exist
    if not os.path.exists(path_folder):
        os.mkdir(path_folder)
        print("Directory " , path_folder ,  " Created ")
    else:    
        print("WARNING: Directory " , path_folder ,  " already exists")

    
    cvfit_log_file = open(os.path.join(path_folder, 'cvfit_log.txt'), "w")

        
    for param_combination in cv_results_params:
        splits = folds.split(X)
        model_current = model.__class__(**param_combination)
        
        for fold, (tr_ind, va_ind) in enumerate(splits):
            fold_str = f"split{fold}_test_score"
            name = model_str(model_current, fold, param_combination)
                
            model_current.fit(X[tr_ind], y[tr_ind])
            
            if scorer:
                if scorer.__name__ ==  "roc_auc_score":
                    test_score_fold = scorer(model_current.predict_proba(X[va_ind]), y[va_ind])
                elif scorer == "roc_auc_score":
                    test_score_fold = roc_auc_score(model_current.predict_proba(X[va_ind]), y[va_ind])
                else:
                    test_score_fold = scorer(model_current.predict(X[va_ind]), y[va_ind])
            else:
                test_score_fold       = model_current.score(X[va_ind], y[va_ind])
            
            cv_results_[fold_str] = np.append(cv_results_[fold_str], test_score_fold) 
            
            line_for_log = name + f" --> test_score={test_score_fold}"
            cvfit_log_file.write(line_for_log + "\n")
            
            if save_models:
                file_path = os.path.join(path_folder, name) 
                fileName = Path(file_path)
            
                if fileName.is_file():
                    print("WARNING: An exact model with the same hyperparameters is trying to be saved")
                    print(f"file {file_path} already exists")
                    return None
                else:
                    joblib.dump(model_current, file_path) 
            
               
            if verbose ==1:
                print(name,f" --> test_score={test_score_fold}")
            
    cvfit_log_file.close()
    test_scores = [cv_results_[f"split{i}_test_score"] for i in range(4)]
    test_scores_arr = np.array(test_scores)
    
    #cv_results_["best_test_score"] = np.max(test_scores_arr)
    cv_results_["mean_test_score"] = test_scores_arr.mean(axis=0)
    cv_results_["std_test_score"] = test_scores_arr.mean(axis=0)

    rank = scipy.stats.rankdata(-cv_results_["mean_test_score"], method='ordinal')
    cv_results_["rank_test_score"] = rank
    # Save in key "best_params" the best combination of hyperparams found
    # index_best  = np.argmax(rf_grid.cv_results_["mean_test_score"])
    # best_params = rf_grid.cv_results_["params"][ind_best]
    # cv_results_["best_params"] = best_params

    if save_summary:
        cv_results_df = pd.DataFrame(cv_results_).sort_values(["rank_test_score"])
        cv_results_df.to_csv( os.path.join(path_folder, "cv_results_df.csv"),index=False)
        
    return cv_results_ 

In [ ]:
cv = 4
rf = sklearn.ensemble.RandomForestRegressor()
path_models = "./saved_models"
cv_results_ = CVfit(X, y, rf, cv, param_grid, scorer=None, 
                    path_folder=path_models, 
                    save_models=True, add_time=False, save_summary=True, verbose=1)


This function returns a dict `cv_results` containing the evaluation metrics of the crossvalidation process

In [ ]:
cv_results_.keys()

In [ ]:
rf_grid.cv_results_.keys()

In [ ]:
os.listdir()

Since we executed with `save_summary=True` we will have `cv_results_df.csv` inside the folder where the models are saved.

In [ ]:
cv_results_df = pd.read_csv( os.path.join(path_models,"cv_results_df.csv"))

In [ ]:
cv_results_df

We can also inspect the log of the cvfit and see the information that is printed when verbose=1

In [ ]:

!cat saved_models/cvfit_log.txt

### TODO: Make a function that given cv_results_df and path_folder...

- Loads different models (topK) and creates a "metamodel". To do so I need to create a new MetaModel class.

    - The metamodel is essentially a list of models: `[m1,m2,m3,...]`
    
    - The metamodel.predict(X) simply does `np.mean(m1.predict(X), m2.predict(X),....)`
    
    - The metamodel should have a weighted average prediction method. 
    
          - The `mean_test_score` could be used to assign a weight into the average
          - The `std_test_score` could be used to assign a confidence of the prediction of the metamodel
      

The models will be saved in `path_folder`

In [ ]:
models = os.listdir(path_models)
models

We can load a model from disk using **`joblib.load`**

In [ ]:
model = joblib.load(os.path.join(path_models, models[0]))
model


# Finding indices with `GroupKFold`

In [386]:
from sklearn.model_selection import GroupKFold

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])
groups = np.array([0, 0, 5, 5])
group_kfold = GroupKFold(n_splits=2)
group_kfold.get_n_splits(X, y, groups)

2

In [387]:
print(group_kfold)

GroupKFold(n_splits=2)


In [388]:
for train_index, test_index in group_kfold.split(X, y, groups):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train, X_test, y_train, y_test)
    print("\n")

TRAIN: [0 1] TEST: [2 3]
[[1 2]
 [3 4]] [[5 6]
 [7 8]] [1 2] [3 4]


TRAIN: [2 3] TEST: [0 1]
[[5 6]
 [7 8]] [[1 2]
 [3 4]] [3 4] [1 2]




In [ ]:
from sklearn import linear_model
from sklearn import neural_network

cv   = sklearn.model_selection.LeaveOneGroupOut()
clf  = sklearn.linear_model.LinearRegression()
grid = sklearn.model_selection.GridSearchCV(clf, param_grid={}, cv=cv, 
                                            return_train_score=True, iid=True, n_jobs=-1)

values_in_col8 = np.array(X_df[8].values, dtype="int")

grid.fit(X,y, groups=values_in_col8)
