<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#SQLIte-DB-connection" data-toc-modified-id="SQLIte-DB-connection-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>SQLIte DB connection</a></span><ul class="toc-item"><li><span><a href="#Connecting/Creating--a-database-sqlite4.connect" data-toc-modified-id="Connecting/Creating--a-database-sqlite4.connect-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Connecting/Creating  a database <code>sqlite4.connect</code></a></span></li><li><span><a href="#Cursor-to-a-database:-conn.cursor" data-toc-modified-id="Cursor-to-a-database:-conn.cursor-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Cursor to a database: <code>conn.cursor</code></a></span></li><li><span><a href="#Executing-SQL-with:-cursor.execute" data-toc-modified-id="Executing-SQL-with:-cursor.execute-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Executing SQL with: <code>cursor.execute</code></a></span></li><li><span><a href="#Using-connection-as-a-context-manager" data-toc-modified-id="Using-connection-as-a-context-manager-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Using connection as a context manager</a></span></li></ul></li><li><span><a href="#Inserting-elements-to-a-DB" data-toc-modified-id="Inserting-elements-to-a-DB-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Inserting elements to a DB</a></span><ul class="toc-item"><li><span><a href="#Inserting-data-to-a-db:-INSERT-INTO-dbname-VALUES-(x0,x1,x2...)" data-toc-modified-id="Inserting-data-to-a-db:-INSERT-INTO-dbname-VALUES-(x0,x1,x2...)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Inserting data to a db: <code>INSERT INTO dbname VALUES (x0,x1,x2...)</code></a></span></li><li><span><a href="#Inserting-data-to-a-table-with-?-notation" data-toc-modified-id="Inserting-data-to-a-table-with-?-notation-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Inserting data to a table with <code>?</code> notation</a></span></li><li><span><a href="#Bulk-insertion-cursor.execute(INSERT-INTO-table_-VALUES-(?,...,?),...,(?,...,?)" data-toc-modified-id="Bulk-insertion-cursor.execute(INSERT-INTO-table_-VALUES-(?,...,?),...,(?,...,?)-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Bulk insertion <code>cursor.execute(INSERT INTO table_ VALUES (?,...,?),...,(?,...,?)</code></a></span></li><li><span><a href="#Bulk-insertion-cursor.executemany(INSERT-INTO-table_-VALUES-(?,...,?))" data-toc-modified-id="Bulk-insertion-cursor.executemany(INSERT-INTO-table_-VALUES-(?,...,?))-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Bulk insertion <code>cursor.executemany(INSERT INTO table_ VALUES (?,...,?))</code></a></span></li></ul></li><li><span><a href="#Fetching/Retriving-items-from-a-DB" data-toc-modified-id="Fetching/Retriving-items-from-a-DB-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Fetching/Retriving items from a DB</a></span><ul class="toc-item"><li><span><a href="#Retriving-all-data-from-table:-&quot;SELECT-*-FROM-vectors&quot;" data-toc-modified-id="Retriving-all-data-from-table:-&quot;SELECT-*-FROM-vectors&quot;-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Retriving all data from table: <code>"SELECT * FROM vectors"</code></a></span></li><li><span><a href="#Retrieve-the-first-item-from-the-query-cursor.fetone()" data-toc-modified-id="Retrieve-the-first-item-from-the-query-cursor.fetone()-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Retrieve the first item from the query <code>cursor.fetone()</code></a></span></li><li><span><a href="#Retrieve-the-first-K-items-from-the-query-cursor.fetchmany(k)" data-toc-modified-id="Retrieve-the-first-K-items-from-the-query-cursor.fetchmany(k)-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Retrieve the first K items from the query <code>cursor.fetchmany(k)</code></a></span></li><li><span><a href="#Retrieve-all--K-items-from-the-query-cursor.fetchall(k)" data-toc-modified-id="Retrieve-all--K-items-from-the-query-cursor.fetchall(k)-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Retrieve all  K items from the query <code>cursor.fetchall(k)</code></a></span></li></ul></li><li><span><a href="#Retrieve-relevant-information-from-the-DB" data-toc-modified-id="Retrieve-relevant-information-from-the-DB-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Retrieve relevant information from the DB</a></span><ul class="toc-item"><li><span><a href="#Number-of-rows" data-toc-modified-id="Number-of-rows-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Number of rows</a></span></li></ul></li><li><span><a href="#Buildin-datatypes-in-SQLITE" data-toc-modified-id="Buildin-datatypes-in-SQLITE-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Buildin datatypes in SQLITE</a></span></li><li><span><a href="#Custom-data-types-in-sqlite" data-toc-modified-id="Custom-data-types-in-sqlite-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Custom data types in sqlite</a></span></li><li><span><a href="#SQLite-Benchmarking" data-toc-modified-id="SQLite-Benchmarking-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>SQLite Benchmarking</a></span></li></ul></div>

Some material

- https://sebastianraschka.com/Articles/2014_sqlite_in_python_tutorial.html

In [1]:
import sqlite3

In [2]:
!rm vectors.db

# SQLIte DB connection

## Connecting/Creating  a database `sqlite4.connect`

We can connect to an in-memory database using `.connect(':memory:')`

In [3]:
help(sqlite3.connect)

Help on built-in function connect in module _sqlite3:

connect(...)
    connect(database[, timeout, detect_types, isolation_level,
            check_same_thread, factory, cached_statements, uri])
    
    Opens a connection to the SQLite database file *database*. You can use
    ":memory:" to open a database connection to a database that resides in
    RAM instead of on disk.



In [4]:
conn_memory = sqlite3.connect(':memory:')

In [5]:
conn_memory

We can connect to an in-disk database using `.connect('name_database.db')`.

This creates a file `name_database.db`.

In [6]:
conn = sqlite3.connect('vectors.db')

Now we should see `vectors.db` in our current folder

In [7]:
ls

SQL.ipynb   vectors.db


Note that the file is empty 

In [8]:
!du vectors.db

0	vectors.db


## Cursor to a database: `conn.cursor`

In [9]:
help(conn.cursor)

Help on built-in function cursor:

cursor(...) method of sqlite3.Connection instance
    Return a cursor for the connection.



In [10]:
cursor = conn.cursor()

## Executing SQL with: `cursor.execute`

We can use  `cursor.execute(sql_statement)` to execute a `sql_statement`.

Note that we need to do `conn.commit()` to ensure that `sql_statement` takes place.

In [11]:
cursor.execute("""CREATE TABLE vectors (
                  id text,
                  price real
                  )""")
conn.commit()
#conn.close()

We can see that the file has already the table

In [12]:
!du vectors.db

16	vectors.db


In [13]:
!cat vectors.db

��

##  Using connection as a context manager


Connection objects can be used as context managers that automatically commit or rollback transactions. In the event of an exception, the transaction is rolled back; otherwise, the transaction is committed:

In [14]:
with conn:
    conn.execute("INSERT INTO vectors VALUES (?, ?)", (221, 221))
    # Successful, con.commit() is called automatically afterwards

In [15]:
cursor.execute("SELECT * FROM vectors")
cursor.fetchall()

[('221', 221.0)]

# Inserting elements to a DB

## Inserting data to a db: `INSERT INTO dbname VALUES (x0,x1,x2...)`

To insert values to table `vectors` we can use the command

```
INSERT INTO vectors VALUES (x0, x1)
```

where `x0` and `x1` are values inserted to the db.

In [16]:
import uuid
#a = uuid.uuid4()
#hex_uuid = a.hex
hex_uuid = '12345'
price = 500

In [17]:
conn = sqlite3.connect('vectors.db')
cursor = conn.cursor()

We can insert data into the DB using an `INSERT` clause in SQL

In [18]:
cursor.execute(f"INSERT INTO vectors VALUES ('{hex_uuid}', {price})")
cursor.execute(f"INSERT INTO vectors VALUES ('{45677}', {price})")
cursor.execute(f"INSERT INTO vectors VALUES ('{89999}', {price})")
cursor.execute(f"INSERT INTO vectors VALUES ('{99999}', 300)")

## Inserting data to a table with `?` notation

Elements can also be introduced using `execute(sql_query, inputs)` which can come in handy
when interacting with data stored in python variables.

This can be done passing:

- SQL query with `?` placeholders and a tuple.
- SQL query with `:name` placeholders and a dictionary

In [19]:
cursor.execute(f"INSERT INTO vectors VALUES (?, ?)", (221, 350))

In [20]:
cursor.execute("INSERT INTO vectors VALUES (:id, :dollars)", 
               {'id':234,'dollars':325})
conn.commit()

In [21]:
cursor.execute("SELECT * FROM vectors")
cursor.fetchall()

[('221', 221.0),
 ('12345', 500.0),
 ('45677', 500.0),
 ('89999', 500.0),
 ('99999', 300.0),
 ('221', 350.0),
 ('234', 325.0)]

## Bulk insertion `cursor.execute(INSERT INTO table_ VALUES (?,...,?),...,(?,...,?)`


If we want to insert N elements, we can call N `cursor.execute(INSERT ...)` 

In [22]:
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
print(f'hex_uuid={hex_uuid}')
print(f'price={price}')
cursor.execute("""CREATE TABLE vectors (
                  id text,
                  price real
                  )""")
cursor.execute(f"INSERT INTO vectors VALUES (?,?),(?,?)",(hex_uuid, price, 221, 56))
cursor.execute("SELECT * FROM vectors")
cursor.fetchall()

hex_uuid=12345
price=500


[('12345', 500.0), ('221', 56.0)]

## Bulk insertion `cursor.executemany(INSERT INTO table_ VALUES (?,...,?))`


We can also leverage `executemany(INSERT..., list_of_items_to_insert)`.

In [23]:
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""CREATE TABLE vectors (
                  id text,
                  price real
                  )""")
cursor.executemany("INSERT INTO vectors VALUES (?,?)", [('12', 23),
                                                        ('23', 34),
                                                        ('45', 56)])
cursor.execute("SELECT * FROM vectors")
cursor.fetchall()

[('12', 23.0), ('23', 34.0), ('45', 56.0)]

# Fetching/Retriving items from a DB



- `cursor.fetone()`: retrieve the first item from the query
- `cursor.fetchmany(k)`: retrieve top k items form the query
- `cursor.fetchall()`: retrieve all items from the query


## Retriving all data from table: `"SELECT * FROM vectors"`

The command  `SELECT * FROM vectors` retrieves all items from table `vectors`.


In [24]:
cursor.execute("SELECT * FROM vectors")
cursor.fetchall()

[('12', 23.0), ('23', 34.0), ('45', 56.0)]

## Retrieve the first item from the query `cursor.fetone()`



Let's see if the data was stored. 

In [25]:
conn = sqlite3.connect('vectors.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM vectors WHERE price=500")
cursor.fetchone()

('12345', 500.0)

## Retrieve the first K items from the query `cursor.fetchmany(k)`


In [26]:
cursor.execute("SELECT * FROM vectors WHERE price=500")
cursor.fetchmany(2)

[('12345', 500.0), ('45677', 500.0)]

In [27]:
conn = sqlite3.connect('vectors.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM vectors WHERE price=500")
cursor.fetchall()

[('12345', 500.0), ('45677', 500.0), ('89999', 500.0)]

## Retrieve all  K items from the query `cursor.fetchall(k)`


We can also call .execute with a pair of inputs as follows:

In [28]:
conn = sqlite3.connect('vectors.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM vectors WHERE price=?", (325,))
cursor.fetchall()

[('234', 325.0)]

In [29]:
conn = sqlite3.connect('vectors.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM vectors WHERE price=:price", {'price':325})
cursor.fetchall()

[('234', 325.0)]


# Retrieve relevant information from the DB

In [30]:
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""CREATE TABLE vectors (
                  id text,
                  price real
                  )""")
cursor.executemany("INSERT INTO vectors VALUES (?,?)", [('12', 23),
                                                        ('23', 34),
                                                        ('45', 56)])
cursor.execute("SELECT * FROM vectors")
cursor.fetchall()

[('12', 23.0), ('23', 34.0), ('45', 56.0)]

In [31]:
cursor.description

(('id', None, None, None, None, None, None),
 ('price', None, None, None, None, None, None))

## Number of rows

We can retrieve the number of rows in the DB using

In [32]:
cursor.execute(f"SELECT * FROM vectors")
cursor.fetchall()

[('12', 23.0), ('23', 34.0), ('45', 56.0)]

In [33]:
cursor.execute("SELECT * FROM vectors")
print(f'len(cursor.fetchall())={len(cursor.fetchall())}')
print(f'cursor.lastrowid={cursor.lastrowid}')

len(cursor.fetchall())=3
cursor.lastrowid=3


In [34]:
cursor.execute("SELECT * FROM vectors WHERE price<25")
print(f'len(cursor.fetchall())={len(cursor.fetchall())}')
print(f'cursor.lastrowid={cursor.lastrowid}')

len(cursor.fetchall())=1
cursor.lastrowid=3


In [35]:
%%timeit 
cursor.execute(f"SELECT * FROM vectors")
len(cursor.fetchall()) 

3.41 µs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
%timeit cursor.lastrowid

36.3 ns ± 0.615 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# Buildin datatypes in SQLITE

SQLite natively supports the following types: NULL, INTEGER, REAL, TEXT, BLOB.

The following Python types can thus be sent to SQLite without any problem:

```
*-------------------------*
|Python type | SQLite type|
*-------------------------*
None           NULL
int            INTEGER
float          REAL
str            TEXT
bytes          BLOB
```
This is how SQLite types are converted to Python types by default:

```
*-------------------------*
|Python type | SQLite type|
*-------------------------*
NULL           None
INTEGER        int
REAL           float
TEXT           depends on text_factory, str by default
BLOB           bytes
```

# Custom data types in sqlite

In [37]:
import numpy as np

class Vector:
    def __init__(self, arg):
        self.arg = arg

    def __str__(self):
        return 'Vector({!r})'.format(self.arg)
    
def adapter(obj: np.ndarray):
    return obj.tobytes()

def converter(data: bytes):
    return np.frombuffer(data)

sqlite3.register_adapter(Vector, adapter)
sqlite3.register_converter(f"{Vector.__name__}", converter)

In [38]:
con = sqlite3.connect(":memory:", detect_types=sqlite3.PARSE_DECLTYPES)
cur = con.cursor()
cur.execute("CREATE TABLE test(v Vector)")
cur.execute("INSERT into test(v) values (?)", (np.array([1.,2.,3.,4.]),))
cur.execute("INSERT into test(v) values (?)", (np.array([2.,3.,4.,5.]),))
cur.execute('SELECT v from test')
cur.fetchall()

[(array([1., 2., 3., 4.]),), (array([2., 3., 4., 5.]),)]

This can cause problems if the datatype is not correctly set

In [39]:
con = sqlite3.connect(":memory:", detect_types=sqlite3.PARSE_DECLTYPES)
cur = con.cursor()
cur.execute("CREATE TABLE test(v Vector)")
cur.execute("INSERT into test(v) values (?)", (np.array([1,2,3,4]),))
cur.execute("INSERT into test(v) values (?)", (np.array([2,3,4,5]),))
cur.execute('SELECT v from test')
cur.fetchall()

[(array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323]),),
 (array([9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323]),)]

In [40]:
cur.execute('select v from test')
vectors = []
for v, in cur.fetchall():
    print(v.shape, v)
    assert isinstance(v, np.ndarray)
    vectors.append(v)

(4,) [4.9e-324 9.9e-324 1.5e-323 2.0e-323]
(4,) [9.9e-324 1.5e-323 2.0e-323 2.5e-323]


To get the correct vector data needs to be interpreted in the correct data type

In [41]:
print(np.frombuffer(vectors[0],dtype=np.int64))
print(np.frombuffer(vectors[1],dtype=np.int64))

[1 2 3 4]
[2 3 4 5]


In [42]:
def adapt_array(arr):
    return arr.tobytes()

def convert_array(bytes):
    return np.frombuffer(bytes)

sqlite3.register_adapter(np.array, adapt_array)    
sqlite3.register_converter("array", convert_array)

In [43]:
con = sqlite3.connect(":memory:", detect_types=sqlite3.PARSE_DECLTYPES)
cur = con.cursor()
cur.execute("CREATE TABLE test(v BLOB)")
cur.execute("INSERT into test(v) values (?)", (np.array([1,2,3,4]),))
cur.execute("INSERT into test(v) values (?)", (np.array([2,3,4,5]),))
cur.execute('SELECT v from test')
cur.fetchall()

cur.execute('select v from test')
vectors = []
for v, in cur.fetchall():
    vectors.append(v)

In [44]:
print(np.frombuffer(vectors[0],dtype=np.int64))
print(np.frombuffer(vectors[1],dtype=np.int64))

[1 2 3 4]
[2 3 4 5]


In [ ]:
%%timeit
cur.execute('SELECT v from test')
cur.fetchall()

In [ ]:
con = sqlite3.connect(":memory:", detect_types=sqlite3.PARSE_DECLTYPES)
cur = con.cursor()
cur.execute("CREATE TABLE vecblob(v BLOB)")
cur.execute("INSERT into vecblob(v) values (?)", (np.array([1,2,3,4]),))
cur.execute("INSERT into vecblob(v) values (?)", (np.array([2,3,4,5]),))
cur.execute('SELECT v from vecblob')
cur.fetchall()

# SQLite Benchmarking

In [ ]:
conn_mem = sqlite3.connect(':memory:')
cursor_mem = conn_mem.cursor()

cursor_mem.execute("""CREATE TABLE vectors (
                  id text,
                  price real
                  )""")

cursor_mem.execute(f"INSERT INTO vectors VALUES ('{hex_uuid}', {price})")
cursor_mem.execute(f"INSERT INTO vectors VALUES ('{45677}', {price})")
cursor_mem.execute(f"INSERT INTO vectors VALUES ('{89999}', {price})")
cursor_mem.execute(f"INSERT INTO vectors VALUES ('{99999}', 300)")

#cursor_mem.commit()
#cursor_mem.close()

We can see that accessing a DB that is in memory is faster than one that is stored on disk

In [ ]:
%%timeit
cursor_mem.execute("SELECT * FROM vectors WHERE price=500")
cursor_mem.fetchall()

In [ ]:
%%timeit
cursor.execute("SELECT * FROM vectors WHERE price=500")
cursor.fetchall()

In [ ]:
cursor_mem.execute("SELECT * FROM vectors WHERE price=500")
cursor_mem.fetchall()