<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Single-prediction" data-toc-modified-id="Single-prediction-0.0.1"><span class="toc-item-num">0.0.1&nbsp;&nbsp;</span>Single prediction</a></span></li></ul></li></ul></li><li><span><a href="#Type" data-toc-modified-id="Type-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Type</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Batch-prediction" data-toc-modified-id="Batch-prediction-1.0.1"><span class="toc-item-num">1.0.1&nbsp;&nbsp;</span>Batch prediction</a></span></li><li><span><a href="#predicting-from-a-string" data-toc-modified-id="predicting-from-a-string-1.0.2"><span class="toc-item-num">1.0.2&nbsp;&nbsp;</span>predicting from a string</a></span></li></ul></li></ul></li></ul></div>

#### Single prediction

In [3]:
import clip
import torch
import torch.utils.data as data
import PIL
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load('ViT-B/32', device)

In [2]:
im = PIL.Image.open('./CLIPImageEncoder/imgs/man_piercing.jpg')

In [4]:
im_tensor_clip_input = preprocess(im).unsqueeze(0)

In [5]:
embedding_tensor = model.encode_image(im_tensor_clip_input)

In [6]:
embedding_np = embedding_tensor.detach().numpy()

In [7]:
embedding_np.shape

(1, 512)

In [23]:
#file = open('./embedding_np.npy','w')
#np.save(file, embedding_np)
#file.close()

In [24]:
clip.tokenize(['hello india'])

tensor([[49406,  3306,  1762, 49407,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]])

In [22]:
model.encode_text(clip.tokenize(['hello india']))

tensor([[ 2.2181e-01, -1.0193e-01,  6.1975e-02,  9.6571e-02, -4.2139e-01,
          1.8021e-02, -4.3130e-02, -1.1107e+00, -2.0959e-01, -6.4504e-02,
          1.3666e-01, -3.4282e-01,  1.9862e-02,  1.3880e-02, -3.0134e-02,
         -4.2100e-02,  4.5357e-01, -2.5192e-01, -1.4415e-01,  4.0770e-03,
          5.1219e-01, -8.8883e-02,  2.0063e-01, -2.6479e-01, -4.0861e-01,
         -1.1505e-01,  4.8988e-02,  1.9275e-01, -1.2737e-01,  1.2102e-01,
         -1.9066e-01, -2.2187e-01,  1.5334e-01, -2.3383e-01, -2.6926e-01,
         -1.6644e-01, -2.2164e-02,  1.0318e-01,  1.0940e-01,  6.6479e-02,
          1.6165e-01, -2.6018e-01,  2.1260e-01, -2.5827e-02, -3.0388e-02,
          3.3561e-01, -1.6371e-01, -2.4495e-01,  2.5352e-01,  1.4817e-02,
          1.9496e-01, -2.4793e-01, -5.7341e-02, -4.2380e-01,  1.0151e-01,
         -2.0547e-01,  5.0810e-02,  2.0005e-01, -8.1289e-02, -1.6582e-01,
          3.6747e-01, -6.5558e-02,  2.3902e-01,  2.0641e-02, -8.0594e-02,
          1.1800e-01, -2.4028e-01,  1.

## Type

In [12]:
type(im_tensor_clip_input)

torch.Tensor

In [15]:
np.array(im_tensor_clip_input).dtype

dtype('float32')

In [9]:
im_tensor_clip_input.detach().numpy().dtype

dtype('float32')

#### Batch prediction

In [8]:
batch = torch.cat([im_tensor_clip_input,
                   im_tensor_clip_input,
                   im_tensor_clip_input])

In [9]:
model.encode_image(batch).shape

torch.Size([3, 512])

#### predicting from a string

In [20]:
clip.tokenize(['hello there', 'this is david'])

tensor([[49406,  3306,   997, 49407,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [49406,   589,   533,  2259, 49407,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0, 

In [22]:
x = clip.tokenize(np.array(['hello there', 'this is david']))
x

tensor([[49406,  3306,   997, 49407,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [49406,   589,   533,  2259, 49407,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0, 

In [24]:
model.encode_text(x).shape

torch.Size([2, 512])