<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction-to-pandas" data-toc-modified-id="Introduction-to-pandas-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction to pandas</a></span><ul class="toc-item"><li><span><a href="#Dataframe-construction-from-numpy-arrays" data-toc-modified-id="Dataframe-construction-from-numpy-arrays-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Dataframe construction from numpy arrays</a></span></li><li><span><a href="#Selecting-columns-of-a-pd.DataFrame" data-toc-modified-id="Selecting-columns-of-a-pd.DataFrame-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Selecting columns of a <code>pd.DataFrame</code></a></span></li><li><span><a href="#Column-types" data-toc-modified-id="Column-types-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Column types</a></span></li><li><span><a href="#Column-hetoregeneity" data-toc-modified-id="Column-hetoregeneity-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Column hetoregeneity</a></span></li></ul></li></ul></div>

# Introduction to pandas

In [1]:
import pandas as pd
import numpy as np
import itertools

## Dataframe construction from numpy arrays 

Pandas Dataframes can be constructed from `np.ndarray` objects

In [105]:
X = np.array([[0,0,5],[7,0,0],[3,3,3]])
X

array([[0, 0, 5],
       [7, 0, 0],
       [3, 3, 3]])

In [106]:
df = pd.DataFrame(X,columns=["a","b","c"])
df

a  b  c
0  0  0  5
1  7  0  0
2  3  3  3

In [107]:
type(df)

pandas.core.frame.DataFrame

## Selecting columns of a `pd.DataFrame`

We can get the information of a column using `df[colname]` for a column named `colname`. 
The returned object of `df[colname]` is a `pd.Series` object.

In [108]:
df["a"]

0    0
1    7
2    3
Name: a, dtype: int64

In [109]:
type(df["a"])

pandas.core.series.Series

We can also use  `df[[colname]]` for a column named `colname`, doing so we generate a pandas dataframe object.

In [110]:
df[["a"]]

a
0  0
1  7
2  3

In [111]:
type(df[["a"]])

pandas.core.frame.DataFrame

## Column types

In [112]:
df.dtypes

a    int64
b    int64
c    int64
dtype: object

## Column hetoregeneity

Columns in a pandas dataframe can be numbers, strings or even arrays

In [113]:
df["a"] = [np.array([2,3,4]),
           np.array([2,3,4]),
           np.array([3,3,2])]

In [114]:
df

a  b  c
0  [2, 3, 4]  0  5
1  [2, 3, 4]  0  0
2  [3, 3, 2]  3  3

In [115]:
df.dtypes

a    object
b     int64
c     int64
dtype: object

In [116]:
df["a"][0]

array([2, 3, 4])

In [117]:
df["a"][1]

array([2, 3, 4])

In [118]:
df["a"][2]

array([3, 3, 2])